synthesio/infra-ovh-ansible-module

plugins/modules/ovh.py

Hi,
Here is a small addition to `install` action to be able to inject "post installation" scripts.
Thank you in advance :-)

feat: inject `postInstallationScriptLink` and `postInstallationScriptReturn` to `install` action

---

plugins/modules/dedicated_server_info.py

Hello,
I would like to be able to fetch information about dedicated servers from the /dedicated/server/{serviceName} api endpoint.
This PR adds a module according to my needs, I thought it might be useful to others.

Add module to fetch server infos.

---

plugins/modules/installation_template.py

Hi,
I noticed hardware raid configuration was working only with RAID0.
I adapted the module to be able to also configure raid1, raid10 and raid60.
I tested the raid configuration against the API, every type of raid seems to be applied fine now (at least the API doesn't yell at me).

Add hardware raid configuration for raid1, raid10 and raid60

---

README.md
plugins/modules/dedicated_server_boot.py
plugins/modules/dedicated_server_display_name.py
plugins/modules/dedicated_server_install_wait.py
plugins/modules/dedicated_server_monitoring.py
plugins/modules/domain.py
plugins/modules/installation_template.py
plugins/modules/public_cloud_flavorid_info.py
plugins/modules/public_cloud_imageid_info.py
plugins/modules/public_cloud_instance.py
plugins/modules/public_cloud_instance_info.py
plugins/modules/public_cloud_monthly_billing.py

Hello, I fix some typo in doc and add some details.

Fix some typo on module name in example and in Documentation

---

README.md
plugins/modules/dedicated_server_install.py

Hello
I've just add the to possibility to deploy with an ssh key (previously added)
Jonas

Add sskKeyName parameter on server deployment

---

README.md
plugins/modules/public_cloud_block_storage.py
plugins/modules/public_cloud_block_storage_instance.py

Add module ansible to create/delete block storage and attach/detach on an instance on ovh public cloud

New ansible module to create/delete block storage and attach/detach

---

.github/workflows/main.yml

Add action from https://github.com/py-actions/flake8

Add flake8 CI with github action

---

README.md
plugins/modules/public_cloud_object_storage.py
plugins/modules/public_cloud_object_storage_policy.py

- Add create/delete support of OVH "High Performance" S3 object storage;
- Allows to apply policy for an existing S3 user on a S3 object storage.

INFRA-8092 Add S3 object storage support

---

README.md

Add append to DNS entry example

---

README.md
plugins/modules/dedicated_server_boot.py
plugins/modules/dedicated_server_boot_wait.py
plugins/modules/dedicated_server_display_name.py
plugins/modules/dedicated_server_info.py
plugins/modules/dedicated_server_install.py
plugins/modules/dedicated_server_install_wait.py
plugins/modules/dedicated_server_monitoring.py
plugins/modules/dedicated_server_networkinterfacecontroller.py
plugins/modules/dedicated_server_terminate.py
plugins/modules/dedicated_server_vrack.py
plugins/modules/domain.py
plugins/modules/installation_template.py
plugins/modules/ip_reverse.py
plugins/modules/public_cloud_flavorid_info.py
plugins/modules/public_cloud_imageid_info.py
plugins/modules/public_cloud_instance.py
plugins/modules/public_cloud_instance_info.py
plugins/modules/public_cloud_monthly_billing.py

Hi there,
Firstly, huge thanks for creating and sharing this incredibly useful module!
I've gone through the README.md and the plugin modules, identifying and rectifying several issues in the provided examples. Additionally, I took the opportunity with this PR to convert all "EXAMPLES" variables to raw string to preserve the formatting.
Looking forward to your feedback!

Fixing examples in README.md and modules

---

plugins/module_utils/ovh.py
plugins/modules/domain.py

Rewriting some part of the domain module to ease its readability.

Enhance domain part of module

---

plugins/modules/public_cloud_instance_interface.py

- Only adding an interface is supported for now

INFRA-9470: New module to attach a network interface to an instance

---

README.md
plugins/modules/ip_info.py

Thank you for your job :pray: 
This is just a tiny suggestion to add a module to retrieve details about a given IP: `ip_info`

feat(modules): add ip_info

---

README.md
plugins/modules/ip_move.py

Thank you for your job :pray: 
This is just a tiny suggestion to add a module to let you change and move an IP to a given server: `ip_move`

feat(modules): add ip_move

---

plugins/modules/domain.py

Build the message to be returned in check mode depending on the action taken.

INFRA-9423: Set message in check mode accordingly to the action taken

---

plugins/modules/installation_template.py

I have error :
Fails calling API (PUT https://eu.api.ovh.com/1.0/me/installationTemplate/MyTemplate): The requested object (templateName = MyTemplate) does not exist
it's indent issue

BUG: Installation_template : Fix after Infra-9559

---

plugins/modules/vps_info.py

Hi,
First code for an Ansible module for retrieving theIinfo of a OVH VPS system.
- Take the Service Name as parameter.
- Report VPS Info
No error handling for the GET (yet).
Based on the dedicated_server_info.py so I kept the author from that one and added mine.
Regards,
Paul Tap (armorica)

VPS Info Module - Supports: Ok

---

plugins/modules/vps_display_name.py

Fix camelcase changes and flake formating.

Fix missing changes on camelcase

---

plugins/modules/domain.py

Use list comprehension to get differences between values recorded and values expected.

Domain: Fix check mode to return diff

---

README.md
plugins/modules/dedicated_server_compatible_templates.py
plugins/modules/domain.py

- Add a module to retrieve compatible templates, based on the code of @balucio
- Fix the domain module for ansible to show changes to be done

Retrieve templates from ovh api; fix domain module to show changes

---

plugins/modules/dedicated_server_boot.py

Fix bootid changes
