synthesio/infra-ovh-ansible-module

plugins/modules/public_cloud_instance.py, plugins/modules/public_cloud_monthly_billing.py
- We can now enable monthly billing when we create an instance
- Or enable it after the creation with the new
public_cloud_monthly_billing
- This can't be disabled
- Update public_cloud_instance options documentations
=> INFRA-6827: Add "monthlyBilling" feature to public cloud instance creation

plugins/modules/public_cloud_flavorid_info.py, plugins/modules/public_cloud_imageid_info.py
- Get flavorId based on commercial name (t1-45, b2-7 etc)
- Get imageId based on human name ("Debian 10", "Centos 7" etc)
- The flavorId and imageId change between region so we can't hardcode it in our playbooks
- By using this module, we can retrieve flavorId and imageId, assign them to variables, and use them to spawn new instances
=> INFRA-6838: Get flavorId and imageId from OVH API

plugins/modules/dedicated_server_display_name.py
- Change the "display name" in ovh manager, so you can use your internal
naming for example
- No need to set internal names in reverse dns anymore
- Change is only visible in OVH manager (and API, of course)
=> INFRA-6896: Add a module to set the "display name" of a dedicated server

plugins/modules/ip_reverse.py
- Reverse API call needs 2 parameters: ipblock and ip.
- On dedicated
instances or cloud instances, both are equal.
- But on vrack ranges, you need to set the "ipBlock" of the IP you want
to add the reverse to.
- This fixes
https://github.com/synthesio/infra-ovh-ansible-module/issues/13
=> INFRA-7027: Allow ip_reverse module to run on vrack IP blocks

plugins/modules/installation_template.py
Hi,
when pushing a software raid template to OVH API, lv type partitions are not pushed correctly. For instance with the following template:
```
templateName: 'proxmoxraid0'
baseTemplateName: 'proxmox6_64'
distribution: 'proxmox6'
customHostname: 'proxmox1.templateraid0'
sshKeyName: 'redacted'
useDistributionKernel: false
defaultLanguage: 'fr'
partitionScheme: 'custom'
partitionSchemePriority: 1
isSoftwareRaid: true
isHardwareRaid: false
lvmReady: true
partition:
- "{'filesystem':'ext4','mountpoint':'/','raid':'0','size':'25000','step':'1','type':'primary'}"
- "{'filesystem':'swap','mountpoint':'swap','raid':'0','size':'4096','step':'2','type':'primary'}"
- "{'filesystem':'ext4','mountpoint':'/var/lib/vz','raid':'0','size':'0','step':'3','type':'lv','volumeName':'data'}" …
```
=> Add volumeName value to partitionScheme partition

plugins/modules/domain.py
This PR only adds DKIM and SPF record types to be able to manage such records using domain plugin
=> domain plugin: Adds support for DKIM and SPF records

README.md, plugins/modules/dedicated_server_install.py
Add the `softRaidDevices` parameter to the call to install a dedicated server using only a provided amount of disks.  
Change camelcase for sshKeyName on ansible side.
=> Allow to specify the number of disks in the raid software

plugins/modules/dedicated_server_networkinterfacecontroller.py, plugins/modules/dedicated_server_vrack.py
- For example on new HGR-SDS-2 instance, there are 2x public + 2x
private interfaces (ready for link aggregations)
- Simply add a fallback to try the "aggregation" route on the API in
case of empty answer on classic call
=> INFRA-7398: Add workaround for new servers with more than 1 interface on the same link

plugins/modules/installation_template.py
Very simple fix to avoid using deprecated yaml call
=> Fixed issue #38 with unsafe parsing of yaml file

plugins/modules/dedicated_server_install_wait.py
- Remove useless Display usage which is broken with ansible-core 2.12+, it should be moved in an action, but we can't use the feature, so remove it
- This fixes https://github.com/synthesio/infra-ovh-ansible-module/issues/48
=> INFRA-8337: Make module compatible with ansible-core 2.12+

README.md, plugins/modules/dedicated_server_boot_wait.py
This PR adds a dedicated_server_boot_wait module for waiting before doing other tasks.
It is based on dedicated_server_install_wait, maybe it would be better to add a generic "dedicated_server_task_wait" module to wait for any tasks..
Anyway i just needed this to do a customized install on my dedicated servers, without using dedicated_server_install.
=> Add dedicated_server_boot_wait

plugins/modules/dedicated_server_install.py
- OVH changed its API behavior on template management for partitionScheme: it used to be "the one with the higher priority will be used by default", but this is not the case anymore
- Add the possibility to specify the partitionSchemeName we want to apply to the dedicated install
=> INFRA-9129: dedicated_server_install: Set partitionSchemeName explicitly on install/start API call

plugins/module_utils/ovh.py, plugins/modules/dedicated_server_boot.py, plugins/modules/dedicated_server_boot_wait.py, plugins/modules/dedicated_server_display_name.py, plugins/modules/dedicated_server_info.py, plugins/modules/dedicated_server_install.py, plugins/modules/dedicated_server_install_wait.py, plugins/modules/dedicated_server_monitoring.py, plugins/modules/dedicated_server_networkinterfacecontroller.py, plugins/modules/dedicated_server_terminate.py, plugins/modules/dedicated_server_vrack.py, plugins/modules/domain.py, plugins/modules/installation_template.py, plugins/modules/ip_info.py, plugins/modules/ip_move.py, plugins/modules/ip_reverse.py, plugins/modules/public_cloud_block_storage.py, plugins/modules/public_cloud_block_storage_instance.py, plugins/modules/public_cloud_flavorid_info.py, plugins/modules/public_cloud_imageid_info.py, plugins/modules/public_cloud_instance.py, plugins/modules/public_cloud_instance_delete.py, plugins/modules/public_cloud_instance_info.py, plugins/modules/public_cloud_instance_interface.py, plugins/modules/public_cloud_monthly_billing.py, plugins/modules/public_cloud_object_storage.py, plugins/modules/public_cloud_object_storage_policy.py
Creating an OVH class in module_utils to abstract calls from modules.
=> Infra-9559: factorization of http calls to OVH API

plugins/modules/public_cloud_instance_interface.py, plugins/modules/public_cloud_private_network_info.py
- Add a module to retrieve private network and return the openstack id of the network matching a given region.
- Modify the module attaching an interface to a public cloud instance to use the openstack id.
=> INFRA-9588: Fix spawning of public cloud instances with private interface

plugins/modules/installation_template.py
__Deprecated, OVH API use language in userMetadata instead.__
Error returned `Some properties does not exist: defaultLanguage`
Refere to api [installationTemplate](https://eu.api.ovh.com/console/?section=%2Fme&branch=v1#post-/me/installationTemplate) and [templateName](https://eu.api.ovh.com/console/?section=%2Fme&branch=v1#put-/me/installationTemplate/-templateName-)
=> installationTemplate: Remove property defaultLanguage to avoid error

plugins/modules/vps_display_name.py
Hi,
First code for an Ansible module for setting the Display Name of OVH VPS system.
- Take the Service Name and Display Name as parameters.
- Check the current value of Display Name for Service Name via GET.
- Set Display Name for Service Name if given value is different.
It was started as a "copy from" the dedicated_server_display_name.py but as that code failed to do anything for my VPS-es I created my own logic. In order to be able to report Changed/Ok/Error it has to do a GET first and then, if necessary do the PUT.
Not sure if the if/then/else catches all possible errors (esp. from the GET).
Regards,
Paul Tap (armorica)
=> VPS Display Name Module - Supports Changed/Ok/Error

plugins/modules/dedicated_server_install.py, plugins/modules/vps_display_name.py
This field allows to push metadata during the intallation
i.e.: The ssh public key can be pushed as shown in the example
It's been tested on my end and should not cause any breaking change as it's not a requiered field and has no impact if not provided
=> feat: add user_metadata to dedicated_server_install module

plugins/modules/dedicated_server_boot.py, plugins/modules/dedicated_server_install.py
- remove rescue (legacy)
- add ipxe-shell and poweroff (formally 'power')
still use static mapping because rescue-customer and ipxe-shell are using the same bootType (rescue) on '/dedicated/server/{serviceName}/boot' API endpoint
=> INFRA-9859: update dedicated server boot option

plugins/modules/dedicated_server_install.py
Adds ability to bypass software raid all together by using the `noRaid` flag: [reference](https://eu.api.ovh.com/console/?section=%2Fdedicated%2Fserver&branch=v1#post-/dedicated/server/-serviceName-/install/start)
The alternative is that an `md` device is created and all the disks are passed in. if 0 disks are specified the api just fails. Using `noRaid` is the only way to fully bypass any `md` device creation and install the os on disk 0, and pass the rest as JBOD
=> Exposes JBOD mode on server installation

plugins/modules/dedicated_server_install.py, plugins/modules/installation_template.py
OVH is removing ssh_key_name usage from it's API, we need to remove it from ovh-ansible module
https://bare-metal-servers.status-ovhcloud.com/incidents/w8l0x9b11qcm
Message from OVH API
```
Fails calling API (POST https://eu.api.ovh.com/1.0/dedicated/server/{serviceName}/install/start):
You are referring to a personal template that contains a sshKeyName parameter that will stop
working starting from the 10th of September 2024. Please fix your personal template and payload
now: https://ovh.to/ECDecxY or wait 60s and retry if you prefer to fix later
```
If you use custom templates, you need to delete them from OVH API if they exist.
Go to the endpoints `/me/installationTemplate` and `DEL /me/installationTemplate/{templateName}`
=> INFRA-9916 remove ssh_key_name reference due to OVH API changes

plugins/modules/dedicated_server_boot.py
Get bootid for each available netboot dynamically from OVH API.  
This will require some changes on ansible side, the calling role must use `hd` instead of `harddisk`
=> INFRA-9996: Get available netboot to send the right bootid

plugins/modules/dedicated_server_hardware_info.py, plugins/modules/dedicated_server_info.py, plugins/modules/dedicated_server_ip_info.py, plugins/modules/dedicated_server_network_info.py
The OVH API exposes additional dedicated server 'info' endpoints, providing values that are not in the base info endpoint. This PR adds three new info modules to retrieve this data, each based on the original info module:
`dedicated/server/{service_name}/specifications/hardware` -> `dedicated_server_hardware_info`
- Detailed processor specifications (cores, threads, architecture)
- Complete disk configurations including RAID options
- Detailed memory specifications
- Hardware model information
`dedicated/server/{service_name}/specifications/ip` -> `dedicated_server_ip_info`
- IP address block details and quotas
- Full IPv4 and IPv6 configuration
`dedicated/server/{service_name}/specifications/network` -> `dedicated_server_network_info`
- Detailed bandwidth and routing configuration
- …
=> Support additional dedicated server info calls

plugins/modules/dedicated_server_boot.py
- Debian 10 rescue image is going to be removed:
<https://bare-metal-servers.status-ovhcloud.com/incidents/41l39x269f6j>
=> INFRA-10376: Add option to boot on Debian 12 rescue image

plugins/modules/dedicated_server_display_name.py
Gets current display name from `/dedicated/server/{service_name}` and changes it only if necessary.
=> Fix change detection in dedicated_server_display_name

plugins/modules/dedicated_server_engagement_strategy.py
This module sets the engagement strategy given the service_name. This is done via the API /services/{serviceId}/billing/engagement/endRule
=> New module dedicated_server_engagement_strategy

plugins/modules/dedicated_server_installation.py
As the old route `install/start` with personal templates is deprecated, we switch to new installation route with parameterized customization and storage configuration.
=> Use new installation route for dedicated servers.

plugins/modules/ip_firewall.py, plugins/modules/ip_firewall_rule.py
These are two new modules to manage the OVH firewall on IP addresses, both for dedicated servers and IP failover.
- ip_firewall: Add, enable and disable the firewall to an OVH IP
- ip_firewall_rule: Add or delete a rule to a firewall
=> New modules for managing OVH firewall
